spring:
  cloud:
    vault:
      #      vault密钥配置
      fail-fast: true
      uri: http://127.0.0.1:8200
      token: ${VAULT_TOKEN}
      scheme: http
      connection-timeout: 5000
      read-timeout: 15000
      kv:
        enabled: true
        backend: my-website-key
        default-context: key
        profile-separator: "/"
        #        ai密钥路径
        ai-path: "ai-token"
        application-name: galGameByHuaJi
  #        关闭spring ai的自动初始化客户端功能,因为他提供的太废物了不支持多客户端动态初始化
  liquibase:
    enabled: false
  config:
    import: optional:vault://
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 10GB
      file-size-threshold: 10MB
      location: D:\temp\tomcat-work\work\Tomcat\localhost\static

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gal?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=true&characterEncoding=utf-8
    username: ${datasource.username}
    password: ${datasource.password}
    #todo 请注意此简单密钥请在上线时修正
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #德鲁伊监控页面
      stat-view-servlet:
        enabled: true
        # todo:上线时千万别用这玩意
        login-username: "HongDouChu"
        login-password: "Vigna_very_loveliness"
        reset-enable: false
        allow: 127.0.0.1

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  cache:
    cache-names: "commentCache,tokenExpire,tokenValid"
    caffeine:
      spec: |
        commentCache.maximumSize=200,expireAfterWrite=20m
        tokenExpire.maximumSize=100,expireAfterWrite=30m
        tokenValid.maximumSize=100,expireAfterWrite=30m
        default.maximumSize=100,expireAfterWrite=60m
  data:
    redis:
      database: 0
      port: 6379
      host: localhost
server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-part-count: 100
    max-part-header-size: 8KB
    max-swallow-size: -1
    max-http-form-post-size: 10GB
  servlet:
    context-path: /MyGalGameByHuaJi
    encoding:
      charset: UTF-8
      enabled: true
      force: true
mybatis:
  mapper-locations: classpath:com/huaji/galgamebyhuaji/dao/mapper/*.xml
  type-aliases-package: com/huaji/galgamebyhuaji/entity
  configuration:
    map-underscore-to-camel-case: true
    #todo 请注意此为简单密钥请在上线时修正
#    密钥系统,从vault里面读取
jwt:
  #  JWT轮换密钥
  secret-key:
  secret-key1:
  secret-key2:
  secret-key3:
  secret-key4:
  #  默认过期时间和初始版本
  expiration-time: 1800000
  current-version: 0
  system-salt:
#系统密钥和固定盐值
encryption:
  fixed-salt:
  aes-key:
mail:
  smtp-authorization-code:
  smtp-email: "1925871606@qq.com"
  smtp-host: "smtp.qq.com"
  smtp-port: "587"
resource-save-path: 'D:\temp\tomcat-work\work\Tomcat\localhost\static'
#资源存放位置
ai:
  chat-record-size: 4
#保留的聊天记录轮数
