spring:
  cloud:
    vault:
      fail-fast: true
      uri: http://127.0.0.1:8200
      token: ${VAULT_TOKEN}
      scheme: http
      connection-timeout: 5000
      read-timeout: 15000
      kv:
        enabled: true
        backend: my-website-key
        default-context: key
        profile-separator: '/'
  liquibase:
    enabled: false
  config:
    import: optional:vault://
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
      file-size-threshold: 10MB
      location: D:\temp\tomcat-work\work\Tomcat\localhost\static

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gal?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=true&characterEncoding=utf-8
    username: ${datasource.username}
    password: ${datasource.password}
    #todo 请注意此简单密钥请在上线时修正
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin123
        reset-enable: false
        allow: 127.0.0.1

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  cache:
    type: caffeine
    cache-names: "commentCache,tokenValid"
    caffeine:
      spec: |
        commentCache.maximumSize=200,expireAfterWrite=20m
        default.maximumSize=100,expireAfterWrite=60m
  data:
    redis:
      database: 0
      port: 6379
      host: localhost
server:
  servlet:
    context-path: /MyGalGameByHuaJi
    encoding:
      charset: UTF-8
      enabled: true
      force: true
mybatis:
  mapper-locations: classpath:com/huaji/galgamebyhuaji/dao/mapper/*.xml
  type-aliases-package: com/huaji/galgamebyhuaji/entity
  configuration:
    map-underscore-to-camel-case: true
    #todo 请注意此为简单密钥请在上线时修正
jwt:
  secret-key:
  secret-key1:
  secret-key2:
  secret-key3:
  secret-key4:
  expiration-time: 1800000
  current-version: 0
  system-salt:
encryption:
  fixed-salt:
  aes-key:
mail:
  smtp-authorization-code:
  smtp-email: "1925871606@qq.com"
  smtp-host: "smtp.qq.com"
  smtp-port: "587"
resource-save-path: D:\temp\tomcat-work\work\Tomcat\localhost\static
